# Usa una imagen base de Python ligera
FROM python:3.11-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requisitos y los instala
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto de los archivos (incluyendo api.py)
COPY . .

# Define el puerto que escuchará la aplicación (Cloud Run espera el 8080)
ENV PORT 8080

# Comando para ejecutar la aplicación (Uvicorn)
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080"]